{% set name = "dead" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dead-{{ version }}.tar.gz
  sha256: e2b53c1ade71fc4aadafa74237b034b622d0bd3d81811d336d64e67083439d76

build:
  entry_points:
    - dead=dead:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - identify

test:
  imports:
    - dead
  commands:
    - pip check
    - dead --help
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/asottile/dead
  summary: dead simple python dead code detection
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
